# This workflow is to validate a schema compatibility before it's taken for review and merge to master

## name of the workflow
name: On Pull Request creation event => Run Schema Registry maven plugin to check new schema compatibility with an older schema version

## GiHub event that triggers the workflow
on:
  #  run this if we want
  #  push:
  #  branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
   ## run job on a GitHub-hosted runner
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2
    - name: Check schema compatibility
      run: mvn schema-registry:test-compatibility --file pom.xml
