# This workflow is to register a schema on merge to master (it was previously checked for compatibility on PR)

name: ON MERGE TO MASTER Register schema using Schema Registry maven plugin

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build with Maven
        run: mvn schema-registry:register --file pom.xml
