# This workflow is to register a schema on merge to master (it was previously checked for compatibility on PR)

name: On Pull Request approval and merge/push to master => Run Schema Registry maven plugin to register new schema

on:
  push:
    branches:
      - master

jobs:
  build:

  #  runs-on: ubuntu-latest

    steps:
   #   - uses: actions/checkout@v2
      - name: Register schema with Schema Registry maven plugin
        run: mvn schema-registry:register --file pom.xml -o
