# This workflow validates a schema compatibility before it's taken for PR review and merged to master

## Name of the workflow
name: On Pull Request creation event => Run Schema Registry maven plugin to check new schema compatibility with an older schema version

on:
  ## GiHub event that triggers the workflow
  pull_request:
    branches: [ master ]

jobs:
  build:
   ## Run the job on a GitHub-hosted runner
   runs-on: ubuntu-latest
   environment: staging
   env:
     sr_url: ${{ secrets.SR_URL }}
     sr_key: ${{ secrets.SR_KEY }}
     sr_secret: ${{ secrets.SR_SECRET }}
   steps:
    - name: "Echo SR URL"
         env:
           SECRETS_VARS: ${{ secrets.SR_URL }}
         run: echo "$SECRETS_VARS"
    - uses: actions/checkout@v2
    ## - name: Check schema compatibility
      ## Use the Confluent Schema Registry maven plugin to check compatibility
     ## run: mvn schema-registry:test-compatibility -Dsr.url=${sr_url} -Dsr.key=${sr_key} -Dsr.secret=${sr_secret} --file pom.xml
