# This workflow validates a schema compatibility before it's taken for PR review and merged to master

## Name of the workflow
name: On Pull Request creation event => Run Schema Registry maven plugin to check new schema compatibility with an older schema version

on:
  ## GiHub event that triggers the workflow
  pull_request:
    branches: [ master ]

jobs:
  build:
   ## Run the job on a GitHub-hosted runner
   runs-on: ubuntu-latest
   environment: staging
   env:
     sr_url: ${{ secrets.SR_URL }}
     sr_key: ${{ secrets.SR_KEY }}
     sr_secret: ${{ secrets.SR_SECRET }}
   steps:
     - uses: actions/checkout@v2
     - name: "Echo SR URL is the "
       run: echo ${{ secrets.SR_URL }}
     - name: Check schema compatibility
       run: mvn schema-registry:test-compatibility -Dsr.url=${{ secrets.SR_URL }} -Dsr.key=${{ secrets.SR_KEY }} -Dsr.secret=${{ secrets.SR_SECRET }} --file pom.xml
